# Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

# Importing the dataset

In [2]:
rent_rf = pd.read_csv('data.csv')

In [3]:
rent_rf 

neighbourhood_group  longitude  latitude        room_type  price  \
0                Brooklyn  -73.97237  40.64749     Private room    149   
1               Manhattan  -73.98377  40.75362  Entire home/apt    225   
2               Manhattan  -73.94190  40.80902     Private room    150   
3                Brooklyn  -73.95976  40.68514  Entire home/apt     89   
4               Manhattan  -73.94399  40.79851  Entire home/apt     80   
...                   ...        ...       ...              ...    ...   
48890            Brooklyn  -73.94995  40.67853     Private room     70   
48891            Brooklyn  -73.93317  40.70184     Private room     40   
48892           Manhattan  -73.94867  40.81475  Entire home/apt    115   
48893           Manhattan  -73.99112  40.75751      Shared room     55   
48894           Manhattan  -73.98933  40.76404     Private room     90   

       minimum_nights  Neighbourhood  RoomType  
0                   1              1         1  
1                   1             -1        -1  
2                   3             -1         1  
3                   1              1        -1  
4                  10             -1        -1  
...               ...            ...       ...  
48890               2              1         1  
48891               4              1         1  
48892              10             -1        -1  
48893               1             -1         0  
48894               7             -1         1  

[48895 rows x 8 columns]

# Generating independent variable(X) and dependent variable(y)

In [9]:
X= rent_rf.drop(columns=['room_type','neighbourhood_group','RoomType'])
X

longitude  latitude  price  minimum_nights  Neighbourhood
0      -73.97237  40.64749    149               1              1
1      -73.98377  40.75362    225               1             -1
2      -73.94190  40.80902    150               3             -1
3      -73.95976  40.68514     89               1              1
4      -73.94399  40.79851     80              10             -1
...          ...       ...    ...             ...            ...
48890  -73.94995  40.67853     70               2              1
48891  -73.93317  40.70184     40               4              1
48892  -73.94867  40.81475    115              10             -1
48893  -73.99112  40.75751     55               1             -1
48894  -73.98933  40.76404     90               7             -1

[48895 rows x 5 columns]

In [11]:
y= rent_rf['RoomType']
y

0        1
1       -1
2        1
3       -1
4       -1
        ..
48890    1
48891    1
48892   -1
48893    0
48894    1
Name: RoomType, Length: 48895, dtype: int64

# Selecting DecisionTreeClassifier as our model and predicting posssible outcome of a single test run 

In [21]:
from sklearn.tree import DecisionTreeClassifier
model =DecisionTreeClassifier()
model.fit(X,y)
predictions=model.predict([[-73.95976,40.64749,149,1,1]])
predictions

C:\Program Files\anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

### From our test run we could see that for long -73.95976 , lat 40.64749 with a price of 149 and a mim nigth of 1 and in Brooklyn(1) our model predicts dat the room avialable is private(1)

# Splitting the dataset into the Training set and Test set and examinig 90% of the data set

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.9)

# Training our model and testing the accuracy of the model on 90% of our dataset

In [33]:
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
model =DecisionTreeClassifier()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

score=accuracy_score(y_test,y_pred)
score

0.7463300459028315

# Making the Confusion Matrix

In [34]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

# Classification Report

In [38]:
from sklearn.metrics import classification_report ,confusion_matrix
class_report =confusion_matrix(y_test, y_pred)
print (classification_report(y_test, y_pred))
print(class_report)

              precision    recall  f1-score   support

          -1       0.79      0.78      0.79     22900
           0       0.22      0.27      0.25      1050
           1       0.73      0.73      0.73     20056

    accuracy                           0.75     44006
   macro avg       0.58      0.59      0.59     44006
weighted avg       0.75      0.75      0.75     44006

[[17922   146  4832]
 [  125   285   640]
 [ 4582   838 14636]]


# 1. Precision - shows the ability of the model to predict outcomes

# 2. Recall - indicates the proportion of actual positive feedbacks of the model being used

# 3. F1-score - combines the pecision and recall of the model

# 4. Support - the number of samples each metric was calculated

# 5. Accuracy - is the accuracy of the model 

# 6. Macro avg - is the avg of precision, recall and f1-score between the classes

# 7. Wighted avg - is the average of precision , recall and f1-score between classes with regard to the number of samples